#FROM  sasdas
#from 
FROM i3c/base/php-apache as d

RUN apt-get update \
    && apt-get install -y zlib1g-dev \
    && apt-get install -y unzip \
    && apt-get install -y libxml2-dev
    
RUN docker-php-ext-install zip \
	&& docker-php-ext-install simplexml
	
#RUN cd /data && curl -sS https://getcomposer.org/installer | php	
	
    
#RUN cd /data && php composer.phar require facebook/webdriver
USER root
RUN mkdir /composer && cd /composer && curl -sS https://getcomposer.org/installer | php

# Add php user so we aren't running as root.
# --no-create-home 
RUN adduser --system --home /home/php php 

RUN chown -R php /composer \
	&& chown -R php /home/php
    
USER php
RUN cd /composer && php composer.phar require facebook/webdriver
USER root
COPY prepareComposer.sh /
RUN chmod a+x /prepareComposer.sh


